### PR TITLE
LPS-75860 Cannot delete values for multi-value properties in System Settings

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:reopen

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54657. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
