### PR TITLE
LPS-76143

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/54696

**Pull request closed without merging**
