### PR TITLE
LPS-77017 Fixing path

### PR DESCRIPTION
**Pull request by rodrigo-e-c-souza**

### CODE REVIEW

**Comment by rodrigo-e-c-souza** [comment]
ci:test

**Comment by rodrigo-e-c-souza** [comment]
ci:test

**Comment by rodrigo-e-c-souza** [comment]
ci:test

**Comment by vicnate5** [comment]
Test fix LGTM

**Comment by pedroqueiroz94** [comment]
@rodrigo-e-c-souza , we still have failing tests related to the Path. :/

**Comment by rodrigo-e-c-souza** [comment]
ci:test

**Comment by rodrigo-e-c-souza** [comment]
LGTM!

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/54892. [See changes here.](https://github.com/pedroqueiroz94/liferay-portal/compare/7b779ee7555c~1...7b779ee7555c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54895. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
