### PR TITLE
LPS-78103 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Resend of https://github.com/pedroqueiroz94/liferay-portal/pull/91 @alinedoleron @rodrigo-e-c-souza

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
Hey @vicnate5 , we're hiring for Frontend Guild here in Brazil. Are you interested? ahahah 

Thanks for the fix, man!

**Comment by alinedoleron** [comment]
@vicnate5 Thank you very much for the fix, and sorry for letting this mistake pass.

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55640. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55641. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
