### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by interaminense** [comment]
LGTM.

**Comment by pedroqueiroz94** [comment]
@alinedoleron , real errors in the tests... Can you double check the kebab menu to add new pages is working? Thanks!

**Comment by alinedoleron** [comment]
Hi @pedroqueiroz94, I checked the kebab and it's working.
I saw the Poshi report and it says: `Element is not present at "//a[@class='form-builder-controls-trigger']"`
Well, I don't understand much about Poshi tests but, is it seaching for a form-builder-controls-trigger class inside an `<a>` tag? If so, I think the test is incorrect because it should click the `<div>`, not the `<a>` tag. See the image below.
screen shot 2018-01-24 at 20 45 38

**Comment by pedroqueiroz94** [comment]
Thanks for the clarification, @alinedoleron! :)

@rodrigo-e-c-souza, can you fix the Poshi tests and send along with this PR? Thanks!

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Created a new PR with path fix: https://github.com/pedroqueiroz94/liferay-portal/pull/59

**Comment by rodrigo-e-c-souza** [comment]
ci:close

**Pull request closed without merging**
