### PR TITLE
LPS-75936 Dead code in master/7.1. Do not backport to 7.0.x

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@pedroqueiroz94 Could you please check if everything is working properly? After that you can send to Brian. Please don't forget to mention him that we can't backport this. We should apply the same to our DDM Form web bundle. 

@topolik Just to let you know we are replacing the bundle **dynamic-data-lists-form-web** by **dynamic-data-mapping-form-web**. We are moving stuff to DDM subrepo and using a different entity to represent a Form instead of sharing DDLRecordSet with DDL.

**Comment by topolik** [comment]
Thanks for the info @leoadb. /cc @lipusz

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53792. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
