### PR TITLE
LPS-77424 update index from request parameter

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
LGTM! :)

**Comment by rafaprax** [comment]
LGTM

**Comment by pedroqueiroz94** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/54964. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
