### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
ci:test

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
resent to https://github.com/pedroqueiroz94/liferay-portal/pull/91

**Comment by alinedoleron** [comment]
ci:close

**Pull request closed without merging**
