### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
@rodrigo-e-c-souza, can you take a look at the tests here? Thanks!

**Comment by rodrigo-e-c-souza** [comment]
Hi @pedroqueiroz94, failures here are related to known issues

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54928. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
