### PR TITLE
LPS-76178

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-76178

Same code than https://github.com/leoadb/liferay-portal/pull/396 + https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/531

I have updated to last master and tested both LPS-69786 and LPS-76010, and they work fine.

My steps:

1. Installed Liferay 7.0 SP1
2. Test both LPS-69786 and LPS-76010 => reproduced
3. Upgrade to master, including my LPS-76178 changes
4. Tested again both LPS => they work fine, without doing any change in Asset Publisher configuration

If you have any question, please let me now

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55213. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
LGTM!

**Comment by rafaprax** [comment]
LGTM

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55217. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
