### PR TITLE
LPS-73309 Change the space between radio buttons

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
@interaminense , I'm closing this due to that conversation we had about the mobile view for this. Can you add the view port for mobile to keep the behavior like it was before? Thanks!!

**Comment by interaminense** [comment]
Yes @pedroqueiroz94! I'll do it.

**Pull request closed without merging**
