### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by alinedoleron** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
@rodrigo-e-c-souza , we have some poshi issues here. Can you please take a look?

**Comment by rodrigo-e-c-souza** [comment]
Resent at: https://github.com/pedroqueiroz94/liferay-portal/pull/86

**Pull request closed without merging**
