### PR TITLE
LPS-77048

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
@alinedoleron Conflicting files. Please resolve conflicts and update the current branch. Thx

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
I created a new PR: https://github.com/pedroqueiroz94/liferay-portal/pull/60

**Comment by alinedoleron** [comment]
ci:close

**Pull request closed without merging**
