### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by rafaprax** [comment]
sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/55204

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Hi @clovisdasilvaneto, there is a bug on this PR :( . Sidebar won't show up again If you add a field and close sidebar by clicking on X button.

**Pull request closed without merging**
