### PR TITLE
LPS-77034 Remove no needed code

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
ci:stop

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/pedroqueiroz94/liferay-portal/pull/47. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/pedroqueiroz94/liferay-portal/pull/47

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54690. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
