### PR TITLE
LPS-76083 adding error message to parent node

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
@clovisdasilvaneto @alinedoleron @matuzalemsteles @interaminense, can you guys review this? :)

**Comment by linolaoj** [comment]
Hi @clovisdasilvaneto ,
Thank you for reviewing this.
I'm not sure if "targetNode" is the best name for this variable, but I added this variable so the error message can be inserted in a parent node and appear after the field.

**Comment by clovisdasilvaneto** [comment]
Hmm, ok, looks good 👍

**Comment by clovisdasilvaneto** [comment]
LGTM.

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54655. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
