### PR TITLE
LPS-61363 Move

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
@pedroqueiroz94 Please forward this one to @marcellustavares when you're done

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1045. [See changes here.](https://github.com/pedroqueiroz94/liferay-portal/compare/3bc63cc~3...3bc63cc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1053. [See changes here.](https://github.com/pedroqueiroz94/liferay-portal/compare/83fcc7f~3...83fcc7f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
