### PR TITLE
LPS-77063 Fixing path

### PR DESCRIPTION
**Pull request by rodrigo-e-c-souza**

### CODE REVIEW

**Comment by rodrigo-e-c-souza** [comment]
ci:test

**Comment by vicnate5** [comment]
@pedroqueiroz94 Test fix from Rodrigo is good.

Still a SF error?

```[java] Exception in thread "main" java.lang.Exception: Found 12 formatting issues:
     [java] 1: Do not import internal class from another module: ./modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-impl/src/main/java/com/liferay/portal/lpkg/deployer/internal/TargetPlatformIndexerProcessCallable.java 20 (SourceCheck:JavaModuleInternalImportsCheck)
     [java] 2: ./modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-api/src/main/resources/com/liferay/portal/lpkg/deployer/util/packageinfo expected:<null> but was:<version 1.0.0>
     [java] 3: ./modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-document-library/src/main/resources/META-INF/resources/document-library.soy expected:<..."field form-control"[
     [java] 							{if $dir}dir="{$dir}"{/if}
     [java] 							{if $readOnly}disabled{/if}
     [java] 							id="inputFile"
     [java] 							type="text"
     [java] 							value="{$fileEntryTitle ? $fileEntryTitle : ''}"]
     [java] 							>
     [java] 						{cal...> but was:<..."field form-control"[ 
     [java] 							{if $dir}dir="{$dir}"{/if} 
     [java] 							{if $readOnly}disabled{/if}
     [java] 							id="inputFile" 
     [java] 							type="text" 
     [java] 							value="{$fileEntryTitle ? $fileEntryTitle : ''}" ]
     [java] 							>
     [java] 						{cal...>
     [java] 4: ./modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/bnd.bnd expected:<....0
     [java] -includeresource:[ ]test-classes/integra...> but was:<....0
     [java] -includeresource:[\
     [java] 	]test-classes/integra...>
     [java] 5: ./modules/core/portal-web-compat/imported-files.properties expected:<.../restore_entry/,\
     [java]   [  html/taglib/ui/rss/,\
     [java]     ]html/taglib/ui/rss_s...> but was:<.../restore_entry/,\
     [java]   [	html/taglib/ui/rss/,\
     [java]   	]html/taglib/ui/rss_s...>
     [java] 6: ./modules/core/util-taglib-compat/imported-files.properties expected:<...iferay/taglib/ui/RSS[SettingsTag.class,\
     [java]     com/liferay/taglib/ui/RSS]Tag.class,\
     [java]     com/...> but was:<...iferay/taglib/ui/RSS[Tag.class,\
     [java]     com/liferay/taglib/ui/RSSSettings]Tag.class,\
     [java]     com/...>
     [java] 7: ./modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/view_templates.jsp expected:<...-buttons>
     [java] 	</c:if>
     [java] 
     [java] []	<%
     [java] 	PortletURL navi...> but was:<...-buttons>
     [java] 	</c:if>
     [java] 
     [java] [
     [java] ]	<%
     [java] 	PortletURL navi...>
     [java] 8: ./portal-web/docroot/html/common/init.jsp expected:<...portal.kernel.util.R[]eleaseInfo" %><%@
     [java] pa...> but was:<...portal.kernel.util.R[SSUtil" %><%@
     [java] page import="com.liferay.portal.kernel.util.R]eleaseInfo" %><%@
     [java] pa...>
     [java] 9: ./modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-api/src/main/java/com/liferay/dynamic/data/mapping/exception/TemplateSmallImageContentException.java expected:<...ore
     [java]  * details.
     [java]  */
     [java] [
     [java] ]package com.liferay....> but was:<...ore
     [java]  * details.
     [java]  */
     [java] []package com.liferay....>
     [java] 10: ./modules/apps/foundation/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/soy/base/BaseClayCardTag.java expected:<...
     [java] import com.liferay.[]portal.kernel.dao.se...> but was:<...
     [java] import com.liferay.[frontend.taglib.clay.servlet.taglib.soy.base.BaseClayTag;
     [java] import com.liferay.]portal.kernel.dao.se...>
     [java] 11: ./modules/apps/web-experience/export-import/export-import-changeset-api/src/main/java/com/liferay/exportimport/changeset/ChangesetEnvironment.java expected:<...ation.ProviderType;
     [java] [
     [java] ]import com.liferay.p...> but was:<...ation.ProviderType;
     [java] []import com.liferay.p...>
     [java] 12: ./modules/apps/web-experience/export-import/export-import-changeset-api/src/main/java/com/liferay/exportimport/changeset/Changeset.java expected:<...ation.ProviderType;
     [java] [
     [java] ]import com.liferay.p...> but was:<...ation.ProviderType;
     [java] []import com.liferay.p...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:374)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:216)
     [echo] The following error occurred while executing this line:
```

**Comment by pedroqueiroz94** [comment]
@vicnate5 I'll check that

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/356. [See changes here.](https://github.com/pedroqueiroz94/liferay-portal/compare/6b517a4c2a04~1...6b517a4c2a04) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
