### PR TITLE
LPS-76591 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Quick fix for https://github.com/brianchandotcom/liferay-portal/pull/53763. Can you check the results here @rodrigo-e-c-souza

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Thanks, @vicnate5 :)

**Comment by pedroqueiroz94** [comment]
I'm gonna hold this for a while, there's a PR to DDL Form Web which I should consider first.

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
