### PR TITLE
LPS-76355

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
LGTM.

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
@rodrigo-e-c-souza, can you take a look at the tests here? Thanks!

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
ci:test

**Comment by rafaprax** [comment]
> Conflicting files
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-select/src/main/resources/META-INF/resources/select_field.js

Could you please resolve the conflicting files and update the current branch? Thx

**Comment by alinedoleron** [comment]
Resent to https://github.com/pedroqueiroz94/liferay-portal/pull/63

**Comment by alinedoleron** [comment]
ci:close

**Pull request closed without merging**
